# -*- coding: utf-8 -*-
"""AAA_Pizza_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnIFnIw1fkOXHcY7kDuNkEqIaIeKQCXZ

опишите рецепты классами
— пусть будет два размера: L и XL
— метод dict() выводит рецепт в виде
словаря

Margherita
* tomato sauce
* mozzarella
* tomatoes

Pepperoni
* tomato sauce
* mozzarella
* pepperoni

Hawaiian
* tomato sauce
* mozzarella
* chicken
* pineapples
"""

import click


class Pizza:
    def __init__(self, name, ingredients, icon="🍕", size="L"):
        self.name = name
        self.ingredients = ingredients
        self.icon = icon
        self.size = size
        self.icon_printer = icon
        if size == "XL":
            self.cooking_time = len(ingredients) * 3
        else:
            self.cooking_time = len(ingredients) * 2

    def beautifier(func):
      def new_menu(self):
        functime = random.randint(2, 100) 
        output = f"💫💫💫💫💫💫💫 {func.__name__}, only {functime} sec 💫💫💫💫\n" + func(self) + "💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫💫\n"
        return output
      return new_menu

    @beautifier
    def menu(self):

        beautiful_string = ""
        for ingredient in self.ingredients:
            beautiful_string += '🥄' + str(ingredient) + '\n'

        self.icon_printer = self.icon
        if self.size == 'XL':
            self.icon_printer += self.icon * 2
        return f"Pizza {self.name} {self.icon_printer}:\n{beautiful_string}"

    def order(self):
        return f"Will cook {self.name} {self.icon_printer} in {self.cooking_time} minutes\n"


@click.command()
@click.argument('name', default='guest')
def hello(name):
    click.echo(f'Hello {name}')


@click.command()
def menu():
    for pizza in pizzas:
        click.echo(pizza.menu())


@click.command()
@click.argument('name')
def order(name):
    for pizza in pizzas:
        if pizza.name == name:
            click.echo(pizza.order)


@click.argument('name')
def hello(count, name):
    for x in range(count):
        click.echo(f"Hello {name}!")


if __name__ == '__main__':
    pizzas = [Pizza("Margherita", ["tomatoes", "tomato sauce", "mozzarella"], "🍟"),
              Pizza("Pepperoni", ["tomato sauce", "pepperoni", "mozzarella"], size="XL"),
              Pizza("Hawaiian", ["tomato sauce", "chicken", "mozzarella", "pineapples"], "🧀")]
    for pizza in pizzas:
        print(pizza.menu())
